### ISSUE TITLE
Logs filling docker image

### ISSUE THREAD

**Issue by ghstridr** [hussainalhaddad/docker-templates#8]
I recently got a warning about my docker image being nearly full. I investigated and found that my 60GB image had over 54GB of logs in the MyJDownloader container. So I have included what logs were available to me after stopping the container.
Hope this helps. Let me know what else I might be able to do to help debug this. 

`30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/update.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/update_b.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/updaterIcon0.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/updaterIcon100.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/updatericon.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/upload.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/url.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/valentine.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/valentine.png.license

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/video.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/wait.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/warning.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/warning_blue.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/warning_green.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/warning_red.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/wizard.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/wrench.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/xmas-gift.png

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/images/xmas-gift.png.license

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(log) ] -> themes/standard/org/jdownloader/sounds/captcha.wav

30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(checkInstallLogForCacheInvalidation) ] -> Invalidate plugin cache, update last modified:/opt/JDownloader/app/jd/plugins/decrypter|true
30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(checkInstallLogForCacheInvalidation) ] -> Invalidate plugin cache, update last modified:/opt/JDownloader/app/jd/plugins/hoster|true
30|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(deleteAllAwfs) ] -> Delete all awf files
Update Message: Installation done. Exit in 00s

1
1|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:06 PM - INFO [ org.jdownloader.update.UpdateManager(setLaunchState) ] -> Launchstate: LAUNCHING_JD

1
1|Log.L.log 5/2/22, 11:06:06 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/JDownloader/app
SevenZipJBinding: null
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/Core.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/Dynamics.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/Filters.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JAntiCaptcha.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDGUI.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDHttp.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDUtils.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/cling-core.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/cling-support.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-http.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-util.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-xml.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bcpkix-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bcprov-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bctls-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/brotli.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/cons.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/debug-disable.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/hexdump.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/libdbus-java.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/unix.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/htmlunit-core-js.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/image4j.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jna.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jna_platform.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/js.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jsyntaxpane.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/synthetica.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/syntheticaJDCustom.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/syntheticaSimple2D.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/proxyVole.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/sevenzipjbinding.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/sevenzipjbindingLinux.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/svgSalamander.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/zip4j.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/extensions/Extraction.jar
1|Log.L.log 5/2/22, 11:06:06 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/JDownloader/app
1|Log.L.log 5/2/22, 11:06:06 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/JDownloader/app
1|Log.L.log 5/2/22, 11:06:06 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/app/cfg/org.jdownloader.settings.GraphicalUserInterfaceSettings.json
1|Log.L.log 5/2/22, 11:06:06 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Load Translation file:/opt/JDownloader/app/translations/org/jdownloader/gui/translate/GuiTranslation.en.lng/null
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 5/2/22, 11:06:07 PM - SEVERE [ org.jdownloader.update.launcher.SecondLevelLauncher.log ] -> Exception thrown at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:635):
java.lang.NoSuchMethodError: org.appwork.storage.JSONMapper.putSerializer(Ljava/lang/Class;Lorg/appwork/storage/JsonSerializer;)Lorg/appwork/storage/JsonSerializer;
at org.jdownloader.startup.Main.main(Main.java:172)
at org.jdownloader.launcher.StandaloneLauncher.launchJDownloader(StandaloneLauncher.java:131)
at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:633)
at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:457)
at org.jdownloader.update.launcher.SecondLevelLauncher.runMain(SecondLevelLauncher.java:224)
at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:132)
at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)

1|org.jdownloader.update.launcher.SecondLevelLauncher.log 5/2/22, 11:06:07 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(launchJDownloader) ] -> Delete versioninfo
org.jdownloader.update.launcher.JDLauncherFailedException: java.lang.NoSuchMethodError: org.appwork.storage.JSONMapper.putSerializer(Ljava/lang/Class;Lorg/appwork/storage/JsonSerializer;)Lorg/appwork/storage/JsonSerializer;
at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:641)
at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:457)
at org.jdownloader.update.launcher.SecondLevelLauncher.runMain(SecondLevelLauncher.java:224)
at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:132)
at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)
Caused by: java.lang.NoSuchMethodError: org.appwork.storage.JSONMapper.putSerializer(Ljava/lang/Class;Lorg/appwork/storage/JsonSerializer;)Lorg/appwork/storage/JsonSerializer;
at org.jdownloader.startup.Main.main(Main.java:172)
at org.jdownloader.launcher.StandaloneLauncher.launchJDownloader(StandaloneLauncher.java:131)
at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:633)
... 9 more
1|Log.L.log 5/2/22, 11:06:07 PM - SEVERE [ Log.L.log ] -> Exception thrown at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:474):
org.jdownloader.update.launcher.JDLauncherFailedException: java.lang.NoSuchMethodError: org.appwork.storage.JSONMapper.putSerializer(Ljava/lang/Class;Lorg/appwork/storage/JsonSerializer;)Lorg/appwork/storage/JsonSerializer;
at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:641)
Start Update
at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:457)
at org.jdownloader.update.launcher.SecondLevelLauncher.runMain(SecondLevelLauncher.java:224)
at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:132)
at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)
Caused by: java.lang.NoSuchMethodError: org.appwork.storage.JSONMapper.putSerializer(Ljava/lang/Class;Lorg/appwork/storage/JsonSerializer;)Lorg/appwork/storage/JsonSerializer;
at org.jdownloader.startup.Main.main(Main.java:172)
at org.jdownloader.launcher.StandaloneLauncher.launchJDownloader(StandaloneLauncher.java:131)
at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:633)
... 9 more

Update Message: Check for updates
Update Progress: 3%

THREAD: 34
34|Log.L.log 5/2/22, 11:06:07 PM - SEVERE [ Log.L.log ] -> Exception thrown at org.jdownloader.update.launcher.SecondLevelLauncher$4.run(SecondLevelLauncher.java:446):
java.lang.InterruptedException: sleep interrupted
Update Progress: -1%
at java.base/java.lang.Thread.sleep(Native Method)
at org.jdownloader.update.launcher.SecondLevelLauncher$4.run(SecondLevelLauncher.java:439)

Update Message: Contact Server...

THREAD: 35
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient(getUpdateOptions) ] -> org.jdownloader.update.JDUpdateClient:getDefaultUpdateOptions:{
"retryCauses" : null,
"jarDiffEnabled" : true,
"deduplicationMode" : "INTRA"
}
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> GET http://update.appwork.org/jcgi/pkg?st=0&rt=SO&jn=JDownloader.jar&pv=9&cv=20190425001&pkh=12f1848a883e733ed40fffff0dae2f35&app=JD&os=LINUX&osr=ALPINE&arch=X86&os64=1&jvm64=1&java=10000002000000&uid=dnt_&urev=16079&srev=-1&surev=-1&ct=Normal&dedup=INTRA&awfcxz=1&dst=-1&lng=en_US&chlg=0&jdiff=1&rev=-1&1651557967019 via [Direct]
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Get Try with Proxy Direct
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection OK: 3377 Bytes loaded
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection:
----------------Request Information-------------
URL: http://update.appwork.org/jcgi/pkg?st=0&rt=SO&jn=JDownloader.jar&pv=9&cv=20190425001&pkh=12f1848a883e733ed40fffff0dae2f35&app=JD&os=LINUX&osr=ALPINE&arch=X86&os64=1&jvm64=1&java=10000002000000&uid=dnt_&urev=16079&srev=-1&surev=-1&ct=Normal&dedup=INTRA&awfcxz=1&dst=-1&lng=en_US&chlg=0&jdiff=1&rev=-1&1651557967019
URL-Parameters:
st : 0
rt : SO
jn : JDownloader.jar
pv : 9
cv : 20190425001
pkh : 12f1848a883e733ed40fffff0dae2f35
app : JD
os : LINUX
osr : ALPINE
arch : X86
os64 : 1
jvm64 : 1
java : 10000002000000
uid : dnt_
urev : 16079
srev : -1
surev : -1
ct : Normal
dedup : INTRA
awfcxz : 1
dst : -1
lng : en_US
chlg : 0
jdiff : 1
rev : -1
: 1651557967019
ConnectIP: update.appwork.org/176.9.34.43:80
Connection-Timeout: 20000ms
Read-Timeout: 60000ms
----------------Request-------------------------
GET /jcgi/pkg?st=0&rt=SO&jn=JDownloader.jar&pv=9&cv=20190425001&pkh=12f1848a883e733ed40fffff0dae2f35&app=JD&os=LINUX&osr=ALPINE&arch=X86&os64=1&jvm64=1&java=10000002000000&uid=dnt_&urev=16079&srev=-1&surev=-1&ct=Normal&dedup=INTRA&awfcxz=1&dst=-1&lng=en_US&chlg=0&jdiff=1&rev=-1&1651557967019 HTTP/1.1
Host: update.appwork.org
Accept-Language: en_US
User-Agent: JDownloader/201707061810
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cache-Control: no-cache, no-store
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Pragma: no-cache
Connection: Close
Accept-Encoding: gzip
----------------Response Information------------
Connection-Time: 173ms
Request-Time: 176ms
----------------Response------------------------
HTTP/1.1 200 OK
Date: Tue, 03 May 2022 06:06:07 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 3377
Connection: close
Server: AppWork GmbH FcgiServer
JCGI: 1
UPD_SRV: 1
------------------------------------------------

35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.transport.Pkg(parseServerResponse) ] -> Serverresponse: {
"changeLogText" : null,
"pong" : null,
"changeLogContentSize" : -1,
"diskSpaceChanges" : {
"" : {
"required" : 65200588,
"changed" : 65200588
}
},
"timeStamp" : 1651557967371,
"uid" : null,
"urls" : [
{
"priority" : 80,
"url" : "http://cdn9.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn7.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn1.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn4.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn6.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn8.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn10.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn11.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
},
{
"priority" : 80,
"url" : "http://cdn12.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0"
}
],
"revisionName" : null,
"updateFlags" : null,
"destRevision" : 16043,
"encrypted" : true,
"size" : 43501600,
"changeLogSize" : -1,
"contentSize" : 66666086,
"changeLogUrls" : null,
"hash" : "562bb165b6e2795ee312835871f235a2da53ffe70383f7df1425dcd342a684b0",
"changeLogHash" : null,
"status" : "URL"
}
Update Message: Check for updates
Update Progress: 5%
Update Message: Prepare Update package...
Update Progress: -1%
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.jdownloader.update.UpdateManager(runUpdateLoop) ] -> Create Packages
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.jdownloader.update.UpdateManager(runUpdateLoop) ] -> Download Packages
Update Message: Download Updates...
Update Progress: 9.75%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> Download UpdatePackage
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> Local File: /opt/JDownloader/app/tmp/update/JD/updatePackage (FileSize: 0|PackageSize:43501600)
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> Download Round:1|Try:0/26|Mirror:http://cdn9.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0|Priority:80
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> Size is 0. Full Download.
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> GET http://cdn9.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0 via [Direct]
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(internalDownloadWithProxy) ] -> Try Proxy: Direct
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Download to /opt/JDownloader/app/tmp/update/JD/updatePackage Size before: 0 bytes
35|org.jdownloader.update.UpdateManager.log 5/2/22, 11:06:07 PM - INFO [ org.appwork.updatesys.client.UpdateClient$11(onConnected) ] -> CDNSignature:VALID (http://cdn9.appwork.org/JD/16043/1651508712838ee7ecaff7dc294152a661a20439159d7_05ebb7fa2d37042f5bf79444c83dcbee1a61445c5-0)
Update Progress: 9.907%
Update Message: Download Updates...
Update Progress: 13.337%
Update Message: Download Updates...
Downloadspeed: 2.96 MB/s, Time left: 12s
Update Progress: 18.081%
Update Message: Download Updates...
Downloadspeed: 4.33 MB/s, Time left: 07s
Update Progress: 23.081%
Update Message: Download Updates...
Downloadspeed: 4.88 MB/s, Time left: 04s
Update Progress: 28.588%
Update Message: Download Updates...
Downloadspeed: 5.47 MB/s, Time left: 03s
Update Progress: 33.276%
Update Message: Download Updates...
Downloadspeed: 5.53 MB/s, Time left: 01s

THREAD: 20
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/8|Priority: 10000]ShutdownController: start item->org.appwork.shutdown.ShutdownRunableEvent Priority: 10000
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/8|Priority: 10000]ShutdownController: item ended after->1
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:1/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/8|Priority: 10000]ShutdownController: start item->flushing logs to disk
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/8|Priority: 10000]ShutdownController: item ended after->6
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:2/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/8|Priority: 0]ShutdownController: start item->ShutdownEvent: Save JSonStorages

THREAD: 41
41|Log.L.log 5/2/22, 11:06:13 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Start Saving Storage
41|Log.L.log 5/2/22, 11:06:13 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> ENDED Saving Storage
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/8|Priority: 0]ShutdownController: item ended after->0
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:3/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/8|Priority: 0]ShutdownController: start item->ShutdownEvent: SaveAllStorageHandler
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/8|Priority: 0]ShutdownController: item ended after->1
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:4/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/8|Priority: 0]ShutdownController: start item->ShutdownEvent: ProcessDelayedWrites num=0
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/8|Priority: 0]ShutdownController: item ended after->0
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:5/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/8|Priority: -2147483648]ShutdownController: start item->org.jdownloader.updatev2.RestartController$1 Priority: -2147483648
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/8|Priority: -2147483648]ShutdownController: item ended after->0
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:6/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/8|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Logging-Cleaner,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/8|Priority: -2147483648]ShutdownController: item ended after->0
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:7/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [8/8|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Logging-Cleaner,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [8/8|Priority: -2147483648]ShutdownController: item ended after->1
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:8/8]
20|org.appwork.shutdown.ShutdownController.log 5/2/22, 11:06:13 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Shutdown Hooks Finished`

**Comment by hussainalhaddad** [comment]
Hi @ghstridr

I've updated the template and solved this issue by mapping JDownloader tmp folder to the host tmp folder
